// frontend/src/App.jsx
import { useEffect } from 'react'
import { useLocation } from 'react-router-dom'
import AppNav from '@/components/layout/AppNav'
import AppFooter from '@/components/layout/AppFooter'
import AppRouter from '@/router'
import { useAuthStore } from '@/stores/auth'

export default function App() {
  const location = useLocation()
  const restoreSession = useAuthStore(s => s.restoreSession)

  useEffect(() => { restoreSession() }, [])

  // Scroll to top on route change
  useEffect(() => { window.scrollTo(0, 0) }, [location.pathname])

  return (
    <div id="wyatt-app">
      <AppNav />
      <main>
        <AppRouter />
      </main>
      <AppFooter />
    </div>
  )
}

// frontend/src/App.vue
<template>
  <div id="wyatt-app">
    <AppNav />
    <main>
      <RouterView v-slot="{ Component }">
        <Transition name="fade" mode="out-in">
          <component :is="Component" />
        </Transition>
      </RouterView>
    </main>
    <AppFooter />
  </div>
</template>

<script setup>
import AppNav from '@/components/layout/AppNav.vue'
import AppFooter from '@/components/layout/AppFooter.vue'
import { useAuthStore } from '@/stores/auth'
import { onMounted } from 'vue'

const auth = useAuthStore()
onMounted(() => auth.restoreSession())
</script>

<style scoped>
#wyatt-app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}
main { flex: 1; }
</style>
